In [ ]:
# Slicing arrays
# Slicing in python means taking elements from one given index to another given index.

# We pass slice instead of index like this: [start:end].

# We can also define the step, like this: [start:end:step].

# If we don't pass start its considered 0

# If we don't pass end its considered length of array in that dimension

# If we don't pass step its considered 1




In [3]:
import numpy as np

arr = np.array([1,3,4,5,6,7])
val = arr[0:6]
print(val)

[1 3 4 5 6 7]


In [38]:
arr = np.array([1,2,3,4,5,6,6,7,7])
print(arr[8:0:-1])

[7 7 6 6 5 4 3 2]


In [42]:
arr = np.array([1,2,3,4,5,6,6,7,7])
print(arr[0:9:1])

[1 2 3 4 5 6 6 7 7]


In [72]:
arr = np.array([1,2,3,4,5,6,7])
n = len(arr)
print(arr[3:n])



[4 5 6 7]


In [75]:
arr = np.array([1,2,3,4,5,6,7])
n = len(arr)
print(arr[-3:-1])

[5 6]


In [83]:
# step

arr = np.array([1,2,3,4,5,6,6])
n = len(arr) -1
val = arr[n:0:-1]
print(val)

[6 5 4 3 2]


In [85]:
arr = np.array([1,3,4,56,77])
val = arr[::2]
print(val)

[ 1  4 77]


In [95]:
# 2d array slicing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[])


[6]


In [97]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]
